### ISSUE TITLE
Specifying destination directory for download

### ISSUE THREAD

**Issue by yic23** [DanielRuf/font-squirrel-downloader#5]
Hi @DanielRuf,
Thanks for the great piece of software.
It would be great to be able to decide where the font files get downloaded to, even if it is just a matter of knowing where to run the command from.

**Comment by DanielRuf** [comment]
Hi @yic23,

you can use now `--dir folder` to define the wanted download target folder.
You can test it using `npm i -g danielruf/font-squirrel-downloader`.

**Comment by DanielRuf** [comment]
Hi @yic23,

The linked commit adds support for `--dir folder` to define the wanted download target folder.
You can test it using `npm i -g danielruf/font-squirrel-downloader`.
